### ISSUE TITLE
Contributing ... or is this abandoned?

### ISSUE THREAD

**Issue by desktophero** [esigler/lita-datadog#3]
Pushing a year since the dependency called out was announced as deprecated: https://github.com/DataDog/dogapi

Would this repo/plugin/handler be considered obsolete or abandoned? If so, I'd like to work on an update ... or maybe there's a better repo. There's a ton of new capabilities available through the dogapi-rb gem that would require some updates to a datadog handler. Tough part is the namespacing in the Lita community to not mess up the community.

Help ... thoughts? :smile:

**Comment by esigler** [comment]
Happy to accept PRs!  I should probably look through and give this some care and feeding as well, it's been a while.

**Comment by esigler** [comment]
@desktophero A question - what features / functionality are you looking for?  Two reasons this plugin hasn't evolved much:

1) The discovery process for a metric or graph is usually so much faster to do in the DD UI and then push back to Slack via @slack-foo mentions.

2) Auto-completing metric names is a serious pain with all of the current chat services.  Github's way around this with their chatops work was to create a custom client that could auto-complete, which is a little outside the scope of this plugin.  :)

One of the things I was thinking about, was an "alias" command, because the common use case "what's up with this box?" has a few fixed sets of graphs, right?  CPU/Memory/Disk/Network, etc.  And so on, for other questions ("what's the work queue pipeline's status?", etc) all could have a basic alias that took a key/value argument for simple things.

**Comment by ehaselwanter** [comment]
I would like to see it updated. reason: It would be cool to be able to react on some incoming webhook and push out the data to a slack channel. this would fit into the 'alias' category as well. I'm doing some PoC around Continuous Delivery and could see this step as a follow up automated push right after finishing the smoke test for deployment.

**Comment by esigler** [comment]
@desktophero - BTW, the deprecated dependency you mentioned is for DataDog's Python library.  Even though the gem is named `dogapi`, the actual library this Ruby plugin uses comes from https://github.com/DataDog/dogapi-rb, which seems in active use to me.
